spring:
  config:
    import: aws-parameterstore:/cloud-assignment/

  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  team:
    name: ${team-name}

app:
  aws:
    s3:
      bucket-name: my-cloud-assignment-profile-images-429496639360